# this file is created to test Dynamic Inventory.. Inventory used is aws-ec2.yaml and playbook is this dynamic.yaml
- name: install few packages
  hosts: all
  become: yes
  tasks:
  - name: install postfix
    ansible.builtin.dnf:
      name: postfix
      state: latest